apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cfg
  namespace: techacademy
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "kube.techacademyit.tk"
    http:
      paths:
      - pathType: Prefix
        path: "/config"
        backend:
          service:
            name: configserver
            port:
              number: 8080
